---
# defaults file for docker
packages_required:
  - dnf-plugins-core
  - git
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - vim
  - bash-completion
